### ISSUE TITLE
Improve and unify selection updating behaviour to handle overlapping ranges

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#138] opened 2021-07-24 21:31 UTC
## The problem
The code in `updateSelections.ts` that actually updates the selections is a bit picky about what it will update.  It works if all edits either

- have no overlap with the given selections, or
- have a range that is identical to one of the selections

However, if, for example, `change.range.start` is not before `selection.range.start`, but is before `selection.range.end`, and not the exact same range, the selections will silently not be updated

One example where the current logic breaks: if the `commentLines` action is applied with a target that is the entire line, the `that` mark ends up not getting moved to the right

In addition, we do not use this new selection updating code in the `NavigationMap`.  

## The solution
We would like to do the following:

### Improve the selection updating code
There are lots of ways we could get fancy, but let's start with something simple.  The approach is to take each selection, and split it into `start` and `end` positions.  Then for each of these positions, if the end of the `change` range is  before or equal to the position, we shift it.  If the change range contains the position, we can have an option passed in by the caller to determine what to do, either expand to include it, contract to exclude it, or throw an exception / remove the selection.  Could maybe just steal the `OpenOpen` / `OpenClosed` etc stuff that VSCode does with [decorations](https://code.visualstudio.com/api/references/vscode-api#DecorationRangeBehavior)

This solution at least allows us to handle changes that are contained entirely within the selection.

- [ ] Improve selection updating code

### Use selection updating code in the navigation map

- [ ] Use selection updating code in the navigation map

**Comment by AndreasArvidsson** [comment] 2021-07-24 21:35
Not updating partially overlapping ranges was something I did by design but they might be edge cases I I hadn't thought about.

**Comment by AndreasArvidsson** [comment] 2021-07-25 02:19
@pokey Are made a few changes in this pr
https://github.com/pokey/cursorless-vscode/pull/140

With these changes I think that comment line works as expectedb

**Comment by AndreasArvidsson** [comment] 2021-08-04 12:36
@pokey I think everything works as expected now. I have assigned this to you so you can check it.

**Closed** 2021-11-07 07:36 UTC
Labels: bug
