### ISSUE TITLE
Decorations break font ligatures

### ISSUE THREAD

**Issue by brxck** [pokey/cursorless-vscode#81] opened 2021-07-07 20:20 UTC
Ligatures between characters are broken when they are decorated.

![ligatures](https://user-images.githubusercontent.com/28877984/124823092-a500a900-df25-11eb-8fd6-a34cbe6a4b13.png)

However, a possible solution also appears in this image: the ligature is preserved when only the last character is decorated.

**Comment by pokey** [comment] 2021-07-07 20:23
duplicate of #71

**Closed by pokey** 2021-07-07 20:23 UTC
