### ISSUE TITLE
Add scope type for arguments list

### ISSUE THREAD

**Issue by AndreasArvidsson** [pokey/cursorless-vscode#522] opened 2022-01-30 15:26 UTC
`bring arg air to arguments bat`
Where air and bat are in two different functions. This will completely overwrite the arguments list in function bat. Excellent for adding the first argument to an empty argument list also.

**Comment by pokey** [comment] 2022-01-30 16:03
duplicate of #493

**Closed by pokey** 2022-01-30 16:03 UTC
