### ISSUE TITLE
"Chuck line" shouldn't highlight the preceeding line

### ISSUE THREAD

**Issue by brxck** [pokey/cursorless-vscode#77] opened 2021-07-07 18:15 UTC
Both the line being deleted and the preceding line are highlighted. I would expect to just highlight the line being deleted.

**Comment by pokey** [comment] 2021-07-07 18:28
Should be fixed along with #26 and #61 when I patch up the line modifier; same root cause, more or less

**Closed** 2021-07-16 09:20 UTC
Labels: bug
